packages:
  - box
  - pak
  - pacman

meta-code:
  - config
  - assert
  - logger
  - futile.logger
  - logr

timing:
  - bench
  - tictoc

pipelines:
  - targets
  - tarchetypes
  - targetopia
  - sqltargets

parallel:
  - future
  - futurize
  - furrr
  - mirai
  - crew
  - progressr
  - parallelly

dplyr backends:
  - dtplyr
  - dbplyr
  - duckplyr

big data:
  - data.table
  - polars
  - duckdb
  - arrow
  - tidytables

read-write:
  - qs
  - qs2
  - nanoparquet
  - fst
  - arrow

surveys:
  - surveyanalaysis
  - srvyr
  - survey
  - sampling
  - anesrake
  - weighting
  - Hmisc

epi:
  - epiR
  - epitools

tables:
  - gt
  - gtsummary
  - modelsummary
  - sjPlot

easystats:
  - easystats
  - insight
  - bayestestR
  - parameters
  - performance
  - effectsize
  - modelbased
  - report
  - correlation
  - see

tidymodels:
  - tidymodels
  - rsample
  - recipes
  - parsnip
  - yardstick
  - workflows
  - tune
  - dials
  - infer
  - broom

xlsx:
  - readxl
  - openxlsx
  - openxlsx2
  - writexl   # ?

other:
  - datadiff # Hadley
  - janitor
  - zeallot  # py multi assignment
  - listenv  # auth same as future
  - collapse # fmedian
  - tidyboot # ?
  - modelr   # older (rsample newer)

